name: Our Workflow
on: pull_request
jobs:
  up:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, GitHub Actions!" > hello.txt
      - uses: actions/upload-artifact@v3
        with:
          name: hello
          path: hello.txt
      - uses: actions/download-artifact@v3
        id: download
        with:
          name: hello
      - run: echo ${{ steps.download.outputs.download-path }}
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: gh pr comment ${{ github.event.number }} --body "Thanks for creating this PR!"
        env:
          GH_TOKEN: ${{ github.token }}
      - run: gh run view ${{ github.run_id }}
        env:
          GH_TOKEN: ${{ github.token }}
